name: N64 Static Recompile ROM

on:
  workflow_dispatch:

jobs:
  recompile:
    runs-on: macos-14

    steps:
      - name: Checkout Repository
        # クォーテーションを確実に閉じ、末尾のミスを修正しました
        uses: 'actions/checkout@v4'
        with:
          submodules: 'recursive'

      - name: Download Base ROM
        run: |
          curl -L "https://drive.google.com/uc?export=download&id=1li77opFkdX7Iv5H6sKidoDIkOd5cLghM" > baserom.z64

      - name: Setup Binary Permissions
        run: |
          chmod +x ./N64Recomp
          chmod +x ./RSPRecomp

      - name: Run Recompiler
        # 出力先フォルダを事前に作成し、パスを通します
        run: |
          mkdir -p output_src
          ./N64Recomp baserom.z64 . --outdir ./output_src

      - name: Upload Generated Source
        uses: 'actions/upload-artifact@v4'
        with:
          name: Recompiled-Source
          path: ./output_src/
