name: N64 Static Recompile ROM

on:
  workflow_dispatch:

jobs:
  recompile:
    runs-on: macos-14

    steps:
      - name: Checkout Repository
        # クォーテーションを確実に閉じ、末尾のミスを修正しました
        uses: 'actions/checkout@v4'
        with:
          submodules: 'recursive'

      - name: Download Base ROM
        run: |
          curl -L "https://drive.google.com/uc?export=download&id=1syMLEf_VHhGqM4UCL02Igera1zOjQiky" > baserom.z64

      - name: Setup Binary Permissions
        run: |
          chmod +x ./N64Recomp
          chmod +x ./RSPRecomp
      - name: Run Recompiler
        # 引数として TOMLファイル を指定します
        run: |
          mkdir -p output_src
          ./N64Recomp sm64_recomp.toml

      - name: Upload Source
        uses: 'actions/upload-artifact@v4'
        with:
          name: SM64-Recompiled-Source
          path: output_src/
